Repository google/shaderc, pull requests merged in 2019-06, with the labels that each got.

#664 Add in missing flags to pass more of the spirv-cross tests
  libshaderc_spvc/include/shaderc/spvc.h
  libshaderc_spvc/include/shaderc/spvc.hpp
  libshaderc_spvc/src/spvc.cc
  spvc/src/main.cc
  spvc/test/known_failures
  spvc/test/run_spirv_cross_tests.py
Labels: enhancement

#658 Change TODO(name) to TODO(issue#) for spvc files
  libshaderc_spvc/include/shaderc/spvc.h
  spvc/src/main.cc
  spvc/test/run_spirv_cross_tests.py
Labels: enhancement

#661 Add details of spvc to README.md
  README.md
Labels: documentation

#668 Update Dockerfile to use Python 3
  Dockerfile
  glslc/test/glslc_test_framework.py
Labels: bugfix

#660 Refactor dup'd arg handling functions into a single location
  glslc/src/main.cc
  libshaderc_util/Android.mk
  libshaderc_util/CMakeLists.txt
  libshaderc_util/include/libshaderc_util/args.h
  libshaderc_util/src/args.cc
  spvc/src/main.cc
Labels: refactoring

#675 Re-introduce SetShaderModel for backwards compatibility
  libshaderc_spvc/include/shaderc/spvc.h
  libshaderc_spvc/include/shaderc/spvc.hpp
  libshaderc_spvc/src/spvc.cc
Labels: bugfix

#689 Roll third_party/spirv-headers 9242862c84fe..9cf7c3a7d2d2 (1 commits)
  DEPS
Labels: autoroller: commit

#690 Roll third_party/spirv-cross 5e9e8918f9a2..fccf1d046204 (1 commits)
  DEPS
Labels: autoroller: commit

#691 Roll third_party/spirv-cross fccf1d046204..00a8539d1ddf (1 commits)
  DEPS
Labels: autoroller: commit

#694 Roll third_party/googletest 076b7f778883..89656ddbe62f (1 commits)
  DEPS
Labels: autoroller: commit

#697 Roll third_party/spirv-headers 9cf7c3a7d2d2..de99d4d834ae (1 commits)
  DEPS
Labels: autoroller: commit

#702 Roll third_party/googletest 89656ddbe62f..af4c2cb098a3 (2 commits)
  DEPS
Labels: autoroller: commit

#703 Roll third_party/googletest af4c2cb098a3..26afdba792e5 (1 commits)
  DEPS
Labels: autoroller: commit

#698 Roll third_party/spirv-cross 00a8539d1ddf..4104e363005a (3 commits)
  DEPS
Labels: autoroller: commit

#707 Roll third_party/googletest 26afdba792e5..f7c178ecb33c (2 commits)
  DEPS
Labels: autoroller: commit

#709 Roll third_party/googletest f7c178ecb33c..e110929a7b49 (2 commits)
  DEPS
Labels: autoroller: commit

#712 Roll third_party/re2 0c95bcce2f1f..848dfb7e1d7b (2 commits)
  DEPS
Labels: autoroller: commit

#715 Roll third_party/googletest e110929a7b49..fd20d1eccef6 (5 commits)
  DEPS
Labels: autoroller: commit

#718 Roll third_party/googletest fd20d1eccef6..176eccfb8f42 (1 commits)
  DEPS
Labels: autoroller: commit

#722 Roll third_party/spirv-cross 4104e363005a..146dc453bcec (2 commits)
  DEPS
Labels: autoroller: commit

#721 Roll third_party/glslang def9662348b0..9db72785beb3 (1 commits)
  DEPS
Labels: autoroller: commit

#738 Extract common test environment bits out into a class
  spvc/test/run_spirv_cross_tests.py
  spvc/test/run_spirv_cross_tests_wrapper.sh
Labels: enhancement

#743 Add jobs flag to spirv cross tests script
  spvc/test/run_spirv_cross_tests.py
Labels: enhancement

#744 Catch low level exceptions instead of crash
  spvc/test/run_spirv_cross_tests.py
Labels: enhancement

#745 Rolling 4 dependencies and update known_failures
  DEPS
  spvc/test/known_failures
Labels: deps

#748 Roll third_party/spirv-cross/ 02b2a1015..d1bdb6d49 (5 commits)
  DEPS
Labels: deps

#747 Enable implicit fallthrough warning and fix examples of
  CMakeLists.txt
  libshaderc_spvc/src/spvc.cc
  spvc/test/known_failures
Labels: enhancement
